### ISSUE TITLE
kml download filename use input log filename as base

### ISSUE THREAD

**Issue by double16** [PX4/flight_review#52]
It would be useful when downloading KML to make the attachment name based off the uploaded log name rather than `track.kml`.

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/e301470f9d3f3502f045a947d0783452b9c5679c. I'll update the server on the next maintenance cycle.

I was slightly hesitant here, because it exposes user-provided data in a non-obvious way. Since we're dealing with logs that can contain sensitive data, I want to be careful with what information goes where.
