### ISSUE TITLE
Power plot filtered current

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#53]
Can we plot filtered current (battery_status.current_filtered_a) instead of current? The remaining percentage is also useful (what most users actually see).

![image](https://user-images.githubusercontent.com/84712/28832557-cef1efc2-76aa-11e7-8342-2d15293bee21.png)

http://logs.px4.io/plot_app?log=25f46bfb-4389-40e7-b06d-07f96094121e#Nav-Power

**Comment by bkueng** [comment]
I decided not to use the filtered current, because it looks almost the same and it can be useful to see non-filtered spikes:
![flight_review_power_filtered_current](https://user-images.githubusercontent.com/281593/28873916-dea0013a-778f-11e7-9831-22e7d7db6c4d.png)


I added the remaining percentage in https://github.com/PX4/flight_review/commit/55b3420b6abd5caa4c7cd9427b884a2a05271261.

**Comment by dagar** [comment]
Thanks
